= Antora UI for drostan.org
// Settings:
:experimental:
:hide-uri-scheme:
:url-project: https://gitlab.com/antora/antora-ui-default
:url-antora: https://antora.org
:url-opendevise: https://opendevise.com

[NOTE]
====
This repository started as a fork of {url-project}[the Antora default UI.]

As of July 2024, I have deviated so much that I consider this almost a separate project.
I do keep the history of the original code,
and so you will see many contributors credited for helping me get to this point.

I also try to keep up with upstream changes to see if they affect my variation.

The branch `drostan` contains my variation of the Antora UI.
====

This project is used to produce a UI bundle that can be used by {url-antora}[Antora] to generated my own documentation site.
You can see it in use at https://notes.drostan.org[^].

My goals:

- I want to use a more minimalistic approach to HTML and CSS,
based on semantic tags and modern CSS features.
- I am looking at Google's Material Design as a design framework,
but trying to use a simpler version for my notes website.
- I want to be able to use the same overall design for my Wordpress site as well.

== Code of Conduct

I am endorsing the https://gitlab.com/antora/antora/-/blob/HEAD/CODE-OF-CONDUCT.adoc[Code of Conduct]
governing the Antora project and its project spaces.

== Copyright and License

Copyright (C) 2017-present OpenDevise Inc. and the Antora Project for the original code.
Copyright (C) 2021-present drostan.org for my own original modifications.

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.

== Authors

Development of Antora is led and sponsored by {url-opendevise}[OpenDevise Inc].
Adaptation for drostan.org is done by Rolf Kleef.
