@startuml
start

partition "First section" {
  if (decision node) then (yes)
    :receive input<
    :Action A;
  else (no)
    :Action B;
    :Object 1]
  endif
}

fork
  :Parallel X;
fork again
  :Parallel Y;
end merge

repeat

  if (done here) then (stop)
    -[dotted]->
    :last action in this
    part of the flow;
    end;
  else
    :continue;
    :send output>
  endif
  
  switch (cases)
  case (case i.)
    :Action i;
  case (case ii.)
    :Action ii;
  case (case iii.)
    :Action iii;
  endswitch

repeat while (Do it again?) is (yes) not (no)

stop
@enduml
