= Treeview folder structure

== Elements

[cols="2*a"]
|===
h|Treeview source
h|Rendering

|
[source, asciidoc]
----
[source, treeview]
....
include::example$treeview.source[]
....
----
|
[source, treeview]
....
include::example$treeview.source[]
....
|===

== Notes

[WARNING]
.Linux `tree` command
====
The `tree` command on Ubuntu seems to include non-breaking spaces in Unicode in its output.
This is not properly interpreted, and results in a mangled display.

Either specify the output to be in ASCII:

    $ tree --noreport -a --dirsfirst --charset=ASCII <folder>

Or replace the Unicode whitespace in the output:

    $ tree --noreport -a --dirsfirst <folder> | sed -e 's/\xC2\xA0/ /g'
====

== Implementation

The source highlighting for treeview is done with two files:

`/src/js/vendor/hljs-treeview.ts` contains regular expressions to match file and folder names,
and to assign CSS class names.

`/src/css/vendor/treeview.css` contains the CSS classes to style each element.
These classes assign icons from several fonts (Material Icons, Font Awesome free, and Font Awesome brands).
