= Add Fonts

This page explains how to add new fonts to your UI.
These instructions assume you've forked the default UI and are able to customize it.

There are three steps involved:

. Add the font to your UI project
. Add a font-face declaration to your stylesheet
. Use the new font in your stylesheet

How you reference the font file in the font-face declaration depends on how you decide to manage it.
You can manage the font with npm or download it manually and add it directly to your UI project.
The following sections describe each approach in turn.

== npm managed

You can use npm to manage the font.
This approach saves you from having to store the font file directly in your UI project.
Here are the steps involved.

. Use npm to install the font files from a package (e.g., https://www.npmjs.com/package/@fontsource/alegreya-sans[@fontsource/alegreya-sans])

 $ npm i --save @fontsource/alegreya-sans

. In _src/css/typefaces.css_, include the declarations for the regular and italic styles:
+
[source,css]
----
@import "@fontsource/alegreya-sans/400.css";
@import "@fontsource/alegreya-sans/400-italic.css";
@import "@fontsource/alegreya-sans/700.css";
@import "@fontsource/alegreya-sans/700-italic.css";
----
+
Vite will then include the font files in the build output.

. Change the CSS to use your newly imported font:
+
[source,css]
----
:root {
  font-family: "Alegreya Sans", sans-serif;
}
----

== Manual

A simpler approach to adding fonts is to store them directly in your project.
Here are the steps involved.

. Download the font files and add them to the [.path]_src/font_ folder.
Create this folder if it does not exist.
. In [.path]_src/css_, add a corresponding CSS file (e.g., [.path]_typeface-open-sans.css_)
. In that file, declare the font face:
+
[source,css]
----
@font-face {
  font-family: "Open Sans";
  font-style: normal;
  font-weight: 400;
  src:
    local("Open Sans"),
    local("Open Sans-Regular"),
    url(../font/open-sans-latin-400.woff) format("woff")
}
----
+
Note that the path is a relative path starting from the [.path]_src/css_ folder to the [.path]_src/font_ folder.
+
You must define one @font-face for each font weight and style combination (e.g., `font-weight: 500` + `font-style: italic`) from the font that you want to use in your stylesheet.

. Import the typeface CSS file you just created into the main stylesheet, [.path]_src/css/site.css_ (adjacent to the other typeface imports):
+
[source,css]
----
@import "typeface-open-sans.css";
----

. Repeat the previous steps for each font style and weight you want to use.
. Change the CSS to use your newly imported font:
+
[source,css]
----
html {
  font-family: "Open Sans", sans;
}
----
