= History and differences
:url-repo: https://gitlab.com/antora/antora-ui-default
:url-vite: https://vitejs.dev


This project started as a fork of the {url-repo}[Antora UI Default UI^] project.
After a period of small adaptations to the UI,
I wanted to make more radical changes to how the code was organised,
and how the UI was built.

The project still maintains the git history of the original Antora UI:

- It is a way to acknowledge the work done by previous contributors.
However, they will probably only recognise traces of their work in the current version.
- It helps me keep track of upstream changes,
to assess whether I should port those to my version.

== Differences with the Default UI

=== Build system

I replaced the Gulp build system with {url-vite}[Vite^].

Vite is much faster than Gulp,
and also comes with a lot of defaults to replace various Gulp tasks and plugins.

NOTE: The new build system does not yet contain the linting done in the original UI project.

This project is hosted on Github instead of Gitlab,
and contains a Github action to automatically publish new releases.

=== Development workflow

The original UI project has a single-page preview mode,
to see changes as you develop the Handlebars templates the CSS, and Javascript.

In this project, there is a "design preview" that serves a static HTML page,
together with the CSS and Javascript (or TypeScript) files for the interface.
With {url-vite}[Vite^]'s development server and hot module reloading,
previewing and testing changes in CSS or Javascript is very fast.

The changes in the HTML then need to be ported to the Handlebars templates.

The project uses Vite to build the UI bundle,
and Antora to generate its own documentation.
This allows for testing the UI in a more realistic environment,
with multiple pages (which may include edge cases for testing).

NOTE: The ambition is to make the design preview work with the Handlebars templates as well,
but this is not yet implemented.

=== Development setup

The project contains a "devcontainer" setup, that can be used in VS Code.
This should make it easier to work with the proper versions of Node.js and npm.

=== Organisation of templates and CSS

The original UI project offers flexibility to override UI templates in many ways.

This project removes some of that flexibility,
but tries to make the templates and CSS code more closely match the semantic structure of the UI.

The HTML and CSS code also relies on quite modern browsers,
without much effort to make things compatible with older browsers.
The Vite configuration could be extended to provide more backward compatibility,
but this is not a priority for this project.
