= Drostan's Antora UI
// URLs:
:url-antora: https://antora.org
:url-repo: https://gitlab.com/antora/antora-ui-default
:url-drostan: https://github.com/rolfkleef/drostan-antora-ui

The {url-drostan}[Drostan Antora UI^] project produces the Drostan UI bundle for documentation sites generated with {url-antora}[Antora^].
It contains the UI assets (page templates, CSS, JavaScript, images, etc.) and a build system.

The build system can be used to preview the UI locally,
and to package it as a UI bundle for consumption by the Antora site generator.

The project started as a fork of the {url-repo}[Antora UI Default^] project.
Over time, many parts have been heavily adapted or rewritten.
See xref:history.adoc[] for an overview of the main changes and differences with the default UI.

This documentation explains how to use this project to set up, customise and manage this UI for a documentation site generated with Antora.
After reading it, you'll be able to:

* [x] Understand how this Antora UI project is structured.
* [x] Set up your environment to work on the UI project.
* [x] Launch a preview to visually inspect the UI.
* [x] Adopt a development workflow to share and accept changes to the UI.
* [x] Package a UI for your documentation site that Antora can use.
