= PlantUML diagrams

== Overview

.UML Diagrams
[plantuml]
....
@startmindmap
* PlantUML
 * UML diagrams
  * Behaviour diagrams
   * Use cases
   * Activities
   * States
   * Interactions
    * Sequences
    * Communication
  * Structure diagrams
   * Classes
   * Objects
   * Packages
   * Components
   * Deployment
 * Other diagrams
  * Mindmaps
  * Work Breakdown Structures (WBS)
  * C4 models
@endmindmap
....

== Use cases

.Use case diagram
[plantuml]
....
@startuml

actor user as "User"
actor developer as "Developer"
actor appman as "Application Manager"
actor dwb as "DataWorkbench"

user <|-- appman
appman <|-right- developer
developer <|-right- dwb

usecase hfeedback as "Get human-readable feedback"
usecase mfeedback as "Get machine-readable feedback"
usecase api as "Access an API"
usecase run as "Run the validator software"
usecase ws as "Access a web service"

(api) <|-- (mfeedback)
(api) <|-- (hfeedback)
(run) <|-- (api)
(ws) <|-- (run)

user --> (ws)

appman -> (api): "access"

developer -down-> (run)

dwb -> (ws): "operate"

@enduml
....

== Activities

.Activity diagram
[plantuml]
....
@startuml
|Client|
start
:Request validation>
->[GET ...?url=...];
|API|
:Get file from URL;
:Send file to validator>
|Validator|
:Run validation;
|API|
:Receive results<
:Deliver results;
|Client|
:Receive validation results<
stop
@enduml
....

== Mindmaps

See the overview of diagrams at the top of the page for an example of a mindmap.

== C4 models

.C4 diagram
[plantuml]
....
@startuml
!include <C4/C4_Container>

Person(editor, "Editor", "Writes and reviews documentation content.")
Person(publisher, "Publisher", "Updates the documentation website and style.")

Boundary(doc_sys, "Documentation system") {
  System(sources, "Content sources", "Stores content material in components and modules.")
  System(sitegen, "Website generator", "Combines sources to produce the documentation website.")
  Rel_R(sources, sitegen, "are input for")
}

System_Ext(tools, "Editing tools", "Support planning and writing content.")
System_Ext(site, "Documentation website", "Informs users and developers.")

Rel(editor, tools, "works with")
Rel(tools, sources, "contribute content material to")
Rel(publisher, sitegen, "configures and runs")
Rel(sitegen, site, "publishes")

Lay_L(publisher, tools)
@enduml
....
