name: Build the Antora UI bundle
on:
  push:
    branches:
      - drostan
  workflow_dispatch:

jobs:
  antora-ui:
    runs-on: ubuntu-latest

    # allow creating a release in the repo
    permissions:
      contents: write

    steps:
      - name: Get the sources
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Antora UI modules
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Bundle
        run: npm run bundle

      - name: Release bundle artifact
        uses: ncipollo/release-action@v1
        with:
          tag: drostan-antora-ui
          allowUpdates: true
          makeLatest: true
          artifacts: "build/ui-bundle.zip"
