name: Build the Antora UI bundle
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  antora-ui:
    runs-on: ubuntu-latest
    container: node:20-bookworm

    # allow creating a release in the repo
    permissions:
      contents: write

    steps:
      - name: Get the sources
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup npm
        run: npm i

      # - name: Lint
      #   run: npm run lint

      - name: Create the UI bundle
        run: npm run bundle

      - name: Release bundle artifact
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          artifacts: "dist/ui-bundle.zip"
