name: Build the Antora UI bundle
on:
  push:
    branches:
      - drostan
  workflow_dispatch:

jobs:
  antora-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Get the sources
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Antora UI modules
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Bundle
        run: npm run bundle

      - name: Save bundle artifact
        uses: actions/upload-artifact@v3
        with:
          name: drostan-antora-ui
          path: build/ui-bundle.zip
